// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareDeliveryPlanner.Infrastructure.Data;

#nullable disable

namespace SoftwareDeliveryPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260417151729_InitialCreate_WithSchemas")]
    partial class InitialCreate_WithSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.Adjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdjEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AdjStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdjType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("AvailabilityPct")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Adjustments", "resource");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("AssignedDev")
                        .HasColumnType("float");

                    b.Property<double?>("AvailableCapacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalendarDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("CumulativeEffort")
                        .HasColumnType("float");

                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxDev")
                        .HasColumnType("float");

                    b.Property<int?>("SchedRank")
                        .HasColumnType("int");

                    b.Property<string>("ServiceStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Allocations", "scheduling");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.CalendarDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AdjCapacity")
                        .HasColumnType("float");

                    b.Property<double>("BaseCapacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalendarDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<string>("DayName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("EffectiveCapacity")
                        .HasColumnType("float");

                    b.Property<string>("HolidayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<double>("RemainingCapacity")
                        .HasColumnType("float");

                    b.Property<double>("ReservedCapacity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DateKey")
                        .IsUnique();

                    b.ToTable("CalendarDays", "scheduling");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HolidayType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.ToTable("Holidays", "resource");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.LookupValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Category", "Code")
                        .IsUnique();

                    b.ToTable("LookupValues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "TaskStatus",
                            Code = "Not Started",
                            DisplayName = "Not Started",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "TaskStatus",
                            Code = "In Progress",
                            DisplayName = "In Progress",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "TaskStatus",
                            Code = "Completed",
                            DisplayName = "Completed",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "DeliveryRisk",
                            Code = "On Track",
                            DisplayName = "On Track",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "DeliveryRisk",
                            Code = "At Risk",
                            DisplayName = "At Risk",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            Category = "DeliveryRisk",
                            Code = "Late",
                            DisplayName = "Late",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "HolidayType",
                            Code = "National",
                            DisplayName = "National",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "HolidayType",
                            Code = "Religious",
                            DisplayName = "Religious",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            Category = "HolidayType",
                            Code = "Company",
                            DisplayName = "Company",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            Category = "AdjustmentType",
                            Code = "Vacation",
                            DisplayName = "Vacation",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = "AdjustmentType",
                            Code = "Training",
                            DisplayName = "Training",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 12,
                            Category = "AdjustmentType",
                            Code = "Sick Leave",
                            DisplayName = "Sick Leave",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 13,
                            Category = "AdjustmentType",
                            Code = "Other",
                            DisplayName = "Other",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 14,
                            Category = "ActiveStatus",
                            Code = "Yes",
                            DisplayName = "Yes",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "ActiveStatus",
                            Code = "No",
                            DisplayName = "No",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 16,
                            Category = "ResourceRole",
                            Code = "Developer",
                            DisplayName = "Developer",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            Category = "ResourceRole",
                            Code = "Senior Developer",
                            DisplayName = "Senior Developer",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            Category = "ResourceRole",
                            Code = "Tech Lead",
                            DisplayName = "Tech Lead",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            Category = "ResourceRole",
                            Code = "QA",
                            DisplayName = "QA",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            Category = "WorkingWeek",
                            Code = "sun_thu",
                            DisplayName = "Sunday - Thursday",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 21,
                            Category = "WorkingWeek",
                            Code = "mon_fri",
                            DisplayName = "Monday - Friday",
                            IsActive = true,
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings", "scheduling");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AssignedDev")
                        .HasColumnType("float");

                    b.Property<string>("AssignedResourceId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryRisk")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DependsOnTaskIds")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("DevEstimation")
                        .HasColumnType("float");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<double>("MaxDev")
                        .HasColumnType("float");

                    b.Property<double?>("OverrideDev")
                        .HasColumnType("float");

                    b.Property<DateTime?>("OverrideStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("SchedulingRank")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("StrictDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("TaskItems", "task");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("AvailabilityPct")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DailyCapacity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId")
                        .IsUnique();

                    b.ToTable("TeamMembers", "resource");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.Adjustment", b =>
                {
                    b.HasOne("SoftwareDeliveryPlanner.Domain.Models.TeamMember", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .HasPrincipalKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SoftwareDeliveryPlanner.Domain.Models.Allocation", b =>
                {
                    b.HasOne("SoftwareDeliveryPlanner.Domain.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .HasPrincipalKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
